-- GENERATED by eq-ai-raid-server/tools/gen-charms.mjs. Do not edit.
--
-- Item ids for the band charms and raid augments that migration 0016
-- inserts, plus the class -> archetype lookup, which is derived from the
-- same class bitmasks the items carry so the two cannot drift apart.
local M = {}

-- archetype -> band -> item id
M.charms = {
	bulwark = { [10] = 900002, [20] = 900004, [30] = 900006, [40] = 900008, [50] = 900010, [60] = 900012, [65] = 900013, [70] = 900014 },
	blade = { [10] = 900034, [20] = 900036, [30] = 900038, [40] = 900040, [50] = 900042, [60] = 900044, [65] = 900045, [70] = 900046 },
	vessel = { [10] = 900066, [20] = 900068, [30] = 900070, [40] = 900072, [50] = 900074, [60] = 900076, [65] = 900077, [70] = 900078 },
	mind = { [10] = 900098, [20] = 900100, [30] = 900102, [40] = 900104, [50] = 900106, [60] = 900108, [65] = 900109, [70] = 900110 },
	harmony = { [10] = 900130, [20] = 900132, [30] = 900134, [40] = 900136, [50] = 900138, [60] = 900140, [65] = 900141, [70] = 900142 },
}

-- archetype -> era -> augment item id
M.augs = {
	bulwark = { [0] = 900200, [1] = 900201, [2] = 900202, [3] = 900203, [4] = 900204, [6] = 900206, [7] = 900207, [8] = 900208, [9] = 900209, [10] = 900210 },
	blade = { [0] = 900232, [1] = 900233, [2] = 900234, [3] = 900235, [4] = 900236, [6] = 900238, [7] = 900239, [8] = 900240, [9] = 900241, [10] = 900242 },
	vessel = { [0] = 900264, [1] = 900265, [2] = 900266, [3] = 900267, [4] = 900268, [6] = 900270, [7] = 900271, [8] = 900272, [9] = 900273, [10] = 900274 },
	mind = { [0] = 900296, [1] = 900297, [2] = 900298, [3] = 900299, [4] = 900300, [6] = 900302, [7] = 900303, [8] = 900304, [9] = 900305, [10] = 900306 },
	harmony = { [0] = 900328, [1] = 900329, [2] = 900330, [3] = 900331, [4] = 900332, [6] = 900334, [7] = 900335, [8] = 900336, [9] = 900337, [10] = 900338 },
}

M.archetype_name = {
	bulwark = "Bulwark",
	blade = "Blade",
	vessel = "Vessel",
	mind = "Mind",
	harmony = "Harmony",
}

-- Display order, so every list reads the same way.
M.archetype_order = { "bulwark", "blade", "vessel", "mind", "harmony" }

-- class id -> archetype, derived from each archetype's class bitmask
M.archetype_for_class = {
	[1] = "bulwark",
	[3] = "bulwark",
	[5] = "bulwark",
	[4] = "blade",
	[7] = "blade",
	[9] = "blade",
	[16] = "blade",
	[2] = "vessel",
	[6] = "vessel",
	[10] = "vessel",
	[11] = "mind",
	[12] = "mind",
	[13] = "mind",
	[14] = "mind",
	[8] = "harmony",
	[15] = "harmony",
}

return M
