-- GENERATED by eq-ai-raid-server/tools/gen-charms.mjs. Do not edit.
--
-- Item ids for the charms and raid augments that migration
-- 0041_exploration_charms_expansion_lines inserts, plus the class -> archetype
-- lookup, which is derived from the same class bitmasks the items carry so
-- the two cannot drift apart.
local M = {}

-- archetype -> band -> item id
M.charms = {
	bulwark = { [10] = 900002, [20] = 900004, [30] = 900006, [40] = 900008, [50] = 900010 },
	blade = { [10] = 900034, [20] = 900036, [30] = 900038, [40] = 900040, [50] = 900042 },
	vessel = { [10] = 900066, [20] = 900068, [30] = 900070, [40] = 900072, [50] = 900074 },
	mind = { [10] = 900098, [20] = 900100, [30] = 900102, [40] = 900104, [50] = 900106 },
	harmony = { [10] = 900130, [20] = 900132, [30] = 900134, [40] = 900136, [50] = 900138 },
}

-- archetype -> expansion line -> item id, for the ladder above band 50.
--
-- Keyed by LINE rather than era so a caller that has a line key does not
-- have to translate; pools.expansions carries the era beside it.
M.line_charms = {
	bulwark = { velious = 900018, luclin = 900019, pop = 900020, god = 900023, omens = 900024, don = 900025, dodh = 900026 },
	blade = { velious = 900050, luclin = 900051, pop = 900052, god = 900055, omens = 900056, don = 900057, dodh = 900058 },
	vessel = { velious = 900082, luclin = 900083, pop = 900084, god = 900087, omens = 900088, don = 900089, dodh = 900090 },
	mind = { velious = 900114, luclin = 900115, pop = 900116, god = 900119, omens = 900120, don = 900121, dodh = 900122 },
	harmony = { velious = 900146, luclin = 900147, pop = 900148, god = 900151, omens = 900152, don = 900153, dodh = 900154 },
}

-- archetype -> era -> augment item id
M.augs = {
	bulwark = { [0] = 900200, [1] = 900201, [2] = 900202, [3] = 900203, [4] = 900204, [6] = 900206, [7] = 900207, [8] = 900208, [9] = 900209, [10] = 900210 },
	blade = { [0] = 900232, [1] = 900233, [2] = 900234, [3] = 900235, [4] = 900236, [6] = 900238, [7] = 900239, [8] = 900240, [9] = 900241, [10] = 900242 },
	vessel = { [0] = 900264, [1] = 900265, [2] = 900266, [3] = 900267, [4] = 900268, [6] = 900270, [7] = 900271, [8] = 900272, [9] = 900273, [10] = 900274 },
	mind = { [0] = 900296, [1] = 900297, [2] = 900298, [3] = 900299, [4] = 900300, [6] = 900302, [7] = 900303, [8] = 900304, [9] = 900305, [10] = 900306 },
	harmony = { [0] = 900328, [1] = 900329, [2] = 900330, [3] = 900331, [4] = 900332, [6] = 900334, [7] = 900335, [8] = 900336, [9] = 900337, [10] = 900338 },
}

M.archetype_name = {
	bulwark = "Bulwark",
	blade = "Blade",
	vessel = "Vessel",
	mind = "Mind",
	harmony = "Harmony",
}

-- Display order, so every list reads the same way.
M.archetype_order = { "bulwark", "blade", "vessel", "mind", "harmony" }

-- class id -> archetype, derived from each archetype's class bitmask
M.archetype_for_class = {
	[1] = "bulwark",
	[3] = "bulwark",
	[5] = "bulwark",
	[4] = "blade",
	[7] = "blade",
	[9] = "blade",
	[16] = "blade",
	[2] = "vessel",
	[6] = "vessel",
	[10] = "vessel",
	[11] = "mind",
	[12] = "mind",
	[13] = "mind",
	[14] = "mind",
	[8] = "harmony",
	[15] = "harmony",
}

return M
