-- GENERATED by eq-ai-raid-server/tools/gen-pools.mjs. Do not edit.
--
-- Source of truth: eq-ai-raid-server/tools/pools.spec.mjs, which names
-- bosses; every id below was resolved from the live database and checked
-- against the band cap and the era ladder. Regenerate rather than patch:
--     node tools/gen-pools.mjs
--
-- boss_index and visit_index are reverse lookups, and they are the reason
-- this file is generated rather than walked at runtime: global_npc.lua fires
-- on EVERY npc death in the zone, so the lookup has to be one hash probe.
local M = {}

M.bands = {
	[10] = {
		range = { 10, 20 },
		reward_level = 20,
		boss_cap = 25,
		required = 3,
		dungeons = {
			{ zone = "crushbone", era = 0, bosses = { 58032 } },
			{ zone = "blackburrow", era = 0, bosses = { 17029, 17032 } },
			{ zone = "befallen", era = 0, bosses = { 36103 } },
			{ zone = "qcat", era = 0, bosses = { 45094 } },
		},
	},
	[20] = {
		range = { 20, 30 },
		reward_level = 30,
		boss_cap = 35,
		required = 3,
		dungeons = {
			{ zone = "najena", era = 0, bosses = { 44100 } },
			{ zone = "guktop", era = 0, bosses = { 65128 } },
			{ zone = "runnyeye", era = 0, bosses = { 11017 } },
			{ zone = "unrest", era = 0, bosses = { 63062 } },
		},
	},
	[30] = {
		range = { 30, 40 },
		reward_level = 40,
		boss_cap = 45,
		required = 2,
		dungeons = {
			{ zone = "soldunga", era = 0, bosses = { 31126 } },
			{ zone = "paw", era = 0, bosses = { 18122 } },
			{ zone = "mistmoore", era = 0, bosses = { 59129 } },
		},
	},
	[40] = {
		range = { 40, 50 },
		reward_level = 50,
		boss_cap = 55,
		required = 3,
		dungeons = {
			{ zone = "gukbottom", era = 0, bosses = { 66146, 66005, 66159 } },
			{ zone = "soldungb", era = 0, bosses = { 32062 } },
			{ zone = "permafrost", era = 0, bosses = { 73039 } },
			{ zone = "kedge", era = 0, bosses = { 64013 } },
		},
	},
}

M.raids = {
	raid0 = {
		era = 0,
		visits = { "hateplane", "fearplane", "airplane", "cazicthule" },
		bosses = { 76007, 72003, 48238 },
	},
}

-- Compass destinations. zone_id is resolved here so the Wayfinder never
-- has to look one up. Coordinates are the game's own exit points from that
-- band's dungeon - solid ground, and NOT the inbound zone line, which would
-- re-trigger and send the player straight back into the dungeon.
M.destinations = {
	[10] = { zone = "qeytoqrg", zone_id = 4, x = -1155, y = 3431, z = 4, h = 260, label = "Qeynos Hills - Blackburrow" },
	[20] = { zone = "innothule", zone_id = 46, x = -812, y = 172, z = -7, h = 65, label = "Innothule Swamp - Guk" },
	[30] = { zone = "lavastorm", zone_id = 27, x = 983, y = 1330, z = -78, h = 94, label = "Lavastorm - Solusek's Eye" },
	[40] = { zone = "everfrost", zone_id = 30, x = -7073, y = 2022, z = -55, h = 136, label = "Everfrost Peaks - Permafrost" },
	hub = { zone = "ecommons", zone_id = 22, x = -235, y = -1497, z = 3.13, h = 254, label = "East Commonlands - the Cartographer" },
}

-- npc_type id -> { zone = <short name>, is_raid = <bool> }
M.boss_index = {
	[11017] = { zone = "runnyeye", is_raid = false },
	[17029] = { zone = "blackburrow", is_raid = false },
	[17032] = { zone = "blackburrow", is_raid = false },
	[18122] = { zone = "paw", is_raid = false },
	[31126] = { zone = "soldunga", is_raid = false },
	[32062] = { zone = "soldungb", is_raid = false },
	[36103] = { zone = "befallen", is_raid = false },
	[44100] = { zone = "najena", is_raid = false },
	[45094] = { zone = "qcat", is_raid = false },
	[48238] = { zone = "cazicthule", is_raid = true },
	[58032] = { zone = "crushbone", is_raid = false },
	[59129] = { zone = "mistmoore", is_raid = false },
	[63062] = { zone = "unrest", is_raid = false },
	[64013] = { zone = "kedge", is_raid = false },
	[65128] = { zone = "guktop", is_raid = false },
	[66005] = { zone = "gukbottom", is_raid = false },
	[66146] = { zone = "gukbottom", is_raid = false },
	[66159] = { zone = "gukbottom", is_raid = false },
	[72003] = { zone = "fearplane", is_raid = true },
	[73039] = { zone = "permafrost", is_raid = false },
	[76007] = { zone = "hateplane", is_raid = true },
}

-- zone short name -> true, for the visit hook
M.visit_index = {
	["airplane"] = true,
	["befallen"] = true,
	["blackburrow"] = true,
	["cazicthule"] = true,
	["crushbone"] = true,
	["fearplane"] = true,
	["gukbottom"] = true,
	["guktop"] = true,
	["hateplane"] = true,
	["kedge"] = true,
	["mistmoore"] = true,
	["najena"] = true,
	["paw"] = true,
	["permafrost"] = true,
	["qcat"] = true,
	["runnyeye"] = true,
	["soldunga"] = true,
	["soldungb"] = true,
	["unrest"] = true,
}

return M
