-- GENERATED by eq-ai-raid-server/tools/gen-charms.mjs. Do not edit.
--
-- Item ids for the band charms and raid augments that migration 0016
-- inserts, plus the class -> archetype lookup, which is derived from the
-- same class bitmasks the items carry so the two cannot drift apart.
local M = {}

-- archetype -> band -> item id
M.charms = {
	bulwark = { [10] = 900002, [20] = 900004, [30] = 900006, [40] = 900008 },
	blade = { [10] = 900034, [20] = 900036, [30] = 900038, [40] = 900040 },
	vessel = { [10] = 900066, [20] = 900068, [30] = 900070, [40] = 900072 },
	mind = { [10] = 900098, [20] = 900100, [30] = 900102, [40] = 900104 },
	harmony = { [10] = 900130, [20] = 900132, [30] = 900134, [40] = 900136 },
}

-- archetype -> era -> augment item id
M.augs = {
	bulwark = { [0] = 900200 },
	blade = { [0] = 900232 },
	vessel = { [0] = 900264 },
	mind = { [0] = 900296 },
	harmony = { [0] = 900328 },
}

M.archetype_name = {
	bulwark = "Bulwark",
	blade = "Blade",
	vessel = "Vessel",
	mind = "Mind",
	harmony = "Harmony",
}

-- Display order, so every list reads the same way.
M.archetype_order = { "bulwark", "blade", "vessel", "mind", "harmony" }

-- class id -> archetype, derived from each archetype's class bitmask
M.archetype_for_class = {
	[1] = "bulwark",
	[3] = "bulwark",
	[5] = "bulwark",
	[4] = "blade",
	[7] = "blade",
	[9] = "blade",
	[16] = "blade",
	[2] = "vessel",
	[6] = "vessel",
	[10] = "vessel",
	[11] = "mind",
	[12] = "mind",
	[13] = "mind",
	[14] = "mind",
	[8] = "harmony",
	[15] = "harmony",
}

return M
